version: "3.9"

services:
  infrastructure:
    container_name: asisya_infrastructure_dev
    build:
      context: ./Infrastructure
      dockerfile: Dockerfile
    image: asisya_infrastructure:dev
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"
      DB_CONNECTION_STRING: "Host=postgres;Port=5432;Database=asisya_db;Username=postgres;Password=postgres"
    depends_on:
      - postgres

  postgres:
    container_name: asisya_postgres_dev
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: asisya_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  asisya_app_dev:
    container_name: asisya_app_dev
    build:
      context: ./asisya-app
      dockerfile: Dockerfile
    image: asisya_app:dev
    ports:
      - "3000:80"
    depends_on:
      - infrastructure

volumes:
  postgres_data:
    name: asisya_postgres_data